[package]
name = "skyblock-raytracer"
version = "1.0.0"
edition = "2021"
description = "Raytracer en CPU escrito a mano en Rust: diorama Skyblock (overworld + nether)"

# raylib SOLO abre la ventana, muestra el framebuffer y lee teclado/mouse.
# Todo el raytracing (álgebra, intersecciones, materiales, ruido, texturas)
# está implementado a mano con la librería estándar.
[dependencies]
raylib = "5.5"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false

# Para iterar rápido en debug sin que sea insoportablemente lento
[profile.dev]
opt-level = 1